# Generated by Django 3.0.6 on 2020-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Six',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='image')),
                ('imagename', models.TextField(max_length=20)),
                ('imageinfo', models.TextField(max_length=300)),
            ],
        ),
    ]
